name: nix
on:
  push:
  pull_request:
  workflow_dispatch:
concurrency:
  group: nix-${{ (github.event_name == 'push' || github.event_name == 'pull_request') && (github.head_ref || github.ref_name) || format('{0}-{1}', github.event_name, github.run_id) }}
  cancel-in-progress: true
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - uses: cachix/cachix-action@v17
        with:
          name: elmerfem
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: nix build
        run: |
          nix build -L
          nix build .#gui -L
          nix build .#full -L
    if: (github.event_name == 'push' && github.ref_name == 'devel') || github.event_name == 'workflow_dispatch'
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: nix flake check
        run: nix flake check -L
    if: github.event_name == 'push' || github.event_name == 'pull_request'
